wrapping response in further checks because it seems like it panics on unwrap() in cases like
thread 'main' panicked at /Users/ilevy/.cargo/git/checkouts/dydx-v3-rust-f7f09fca4880da3a/fa5773c/src/modules/public.rs:232:58:
called `Result::unwrap()` on an `Err` value: reqwest::Error { kind: Body, source: TimedOut }
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1653:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/result.rs:1077:23
   4: dydx_v3_rust::modules::public::Public::get::{{closure}}
             at /Users/ilevy/.cargo/git/checkouts/dydx-v3-rust-f7f09fca4880da3a/fa5773c/src/modules/public.rs:232:31
   5: dydx_v3_rust::modules::public::Public::get_markets::{{closure}}
             at /Users/ilevy/.cargo/git/checkouts/dydx-v3-rust-f7f09fca4880da3a/fa5773c/src/modules/public.rs:32:55
   6: dca_trading_bot::backtest::utils::get_dydx_market_data::{{closure}}
             at ./src/backtest/utils.rs:76:107
   7: dca_trading_bot::backtest::utils::get_market_data_with_retry::{{closure}}
             at ./src/backtest/utils.rs:88:48
   8: dca_trading_bot::backtest::permutations::Permutator::get_market_data::{{closure}}
             at ./src/backtest/permutations.rs:381:67
   9: dca_trading_bot::backtest::permutations::Permutator::next::{{closure}}
             at ./src/backtest/permutations.rs:420:49
  10: dca_trading_bot::backtest::permutations::Permutator::skip_until::{{closure}}
             at ./src/backtest/permutations.rs:323:42
  11: dca_trading_bot::backtest::manager::BacktestManager::init::{{closure}}
             at ./src/backtest/manager.rs:33:110
  12: dca_trading_bot::backtest::backtest_manager_console::{{closure}}